# Generated by Django 2.2.3 on 2019-07-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('own_date', models.DateTimeField(verbose_name='date published')),
                ('min_players', models.IntegerField(default=0)),
                ('max_players', models.IntegerField(default=0)),
                ('game_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Genre')),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Type')),
            ],
        ),
    ]
