# Generated by Django 2.2.3 on 2019-07-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20190721_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='own_date',
            field=models.IntegerField(default=2000),
        ),
    ]
