# Generated by Django 3.2.5 on 2022-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bgg_id',
            field=models.IntegerField(default=0),
        ),
    ]
